COVOLUME : COVOLUME.for COVOLU.INC  CPGAMMA.INC  GAMTOL.INC  GLOBAL.INC  IC.INC  STARSO.INC  STATES.INC READIC.INC COMIC.INC
	gfortran COVOLUME.for -oCOVOLUME

clean:
	rm -rf COVOLUME
	rm -rf pressure.dat velocity.dat density.dat energy.dat